### ISSUE TITLE
Test lab dataset from DropBox

### ISSUE THREAD

**Issue by JimBuchanan** [SafetyGraphics/hep-explorer#144]
Test the tool with the lab dataset on DropBox from Jim

**Comment by jwildfire** [comment]
@JimBuchanan New Example is set up [here](https://bl.ocks.org/jwildfire/raw/3ccfa6ef3e8a1cd259bbde89f52f6560/), but there is a bug when you click a point, so the details view isn't working (captured as #154). Will work on cleaning that up next week.

**Comment by jwildfire** [comment]
Working well in latest build - will be functional online once v0.14.0 is released.
