### ISSUE TITLE
Add support for "Analysis" Flag

### ISSUE THREAD

**Issue by hongmuw** [SafetyGraphics/hep-explorer#159]
do we use all records to calculate max value for BILI? I just wonder if there is pre screening record, and it is the max value, are we going to choose this one as Max? do we use on treatment flag to subset?

**Comment by jwildfire** [comment]
Very good question. 

> do we use all records to calculate max value for BILI?

The short answer is: Yes, we do!

> if there is pre screening record, and it is the max value, are we going to choose this one as Max?

Again, yes (though this is clearly not ideal)

> do we use on treatment flag to subset?

Not, by default. Although it is certainly possible to add it as an interactive filter (just like race or sex on the example page), and then allow the user to interactively filter. 

I think there are basically 2 paths forward here: 

1) Update the data spec to clarify that the data should be filtered to remove all pre-baseline measures before loading the data in to the visualization tool.
2) Add support for some kind of data driven "on treatment" subsetting that removes the pre-treatment (or post-study follow-up) records from the eDish calculations. 

I'd lean towards option (1) for the v1.0 release, but definitely think that option (2) is reasonable for a future update. What do you think?

**Comment by jwildfire** [comment]
In fact, I've gone ahead and added a note in the data guidelines wiki to clarify the behaviour in the current build. We can update if/when we change the behavior of the tool.

**Comment by hongmuw** [comment]
I think ideally when we calculate the MAX value, we only use after treatment by default (can use analysis flag if use ADaM dataset or use epoch flag if use SDTM dataset), but when we draw individual line, we should display all points including pre-screening and post-treatment points. what do you think?

**Comment by jwildfire** [comment]
Makes sense to me. Let's discuss details and timeline on our next call.

**Comment by jwildfire** [comment]
The more I think about this, the more I think it's worth doing before v1.0. Adding it to a v0.14 release.
