### ISSUE TITLE
Numeric Filters Not working in hep explorer chart

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/hep-explorer#249]
Selecting a numeric variable in settings causes the edish chart to not render any points - regardless of what's selected in the filter.

I think this is more of a hep explorer problem but put it here for now to keep track of it

**Comment by jwildfire** [comment]
Issue occurs when the raw json object has numeric values. This is fairly rare in our javascript examples since d3.csv coerces all values to character, but is an issue in other frameworks (like the 
safetyGraphics R package).
