### ISSUE TITLE
Think about animating by visit instead of by study day to sync movements across participants.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/hep-explorer#257]

**Comment by jwildfire** [comment]
Problem with this is that study day is the only truly required timing variable. Would definitely be easier to handle animation by (numeric) visit in most cases though. I guess we could just say that you only get the cross-sectional view if you include a visit number. 

I guess I'm leaning against doing this for now, but if we're still stuck with a somewhat buggy implementation after another day or 2, we might want to try it ...

**Comment by jwildfire** [comment]
The by-day animation is working fairly well now, so closing this as won't fix.
