### ISSUE TITLE
Dot the hysteresis of measurements after the selected study day/visit.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/hep-explorer#261]

**Comment by jwildfire** [comment]
So, when you click a point, have part of the line dotted if a certain date is selected ... cute idea.

**Comment by jwildfire** [comment]
@samussiah I think this is pretty complicated to implement with our current dash-array animation hack. Going to mark won't fix and close. Feel free to reopen if you've got a good idea for how to implement without too much hassle.
