### ISSUE TITLE
Study day of animation should always be visible.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/hep-explorer#291]
for example with four filters the Study Day control can't be viewed with the chart.

**Comment by jwildfire** [comment]
Options: 
1. Put study day control at the top of the sidebar
2. Put the study day control above or below the chart itself 
3. Make the controls (sidebar) and chart div scroll independently

I think I'd vote for 2, 3, 1 in that order. Don't love any of these though ...
