### ISSUE TITLE
add support for PAlt calculation

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/hep-explorer#301]
Add support for the new PALT measure derived [here](https://www.ncbi.nlm.nih.gov/pubmed/30303523). Formula is below for reference: 

![image](https://user-images.githubusercontent.com/3680095/63791855-32e2c600-c8b1-11e9-9eb7-1b775d4c62dd.png)

[test page](https://bl.ocks.org/jwildfire/raw/e6ac55558cd71f8bd5e46ba35cf6e991)

# Test notes
* A new filter labeled _ALT Elevated?_ appears in the _Filters_ section of the controls with two options: _No_ and _Yes_.
* Select _Yes_ and verify that only those participants with a maximum ALT result greater than three times the upper limit of normal appear.
* Click a point and verify that the P<sub>ALT</sub> calculation appears in the _Participant Details_ section beneath the chart.
* Click the P<sub>ALT</sub> calculation and verify a footnote appears with the formula.

**Comment by jwildfire** [comment]
Demo page here: https://bl.ocks.org/jwildfire/e6ac55558cd71f8bd5e46ba35cf6e991

**Comment by dschwentker** [comment]
Tested and confirmed new filter appears and functions as expected, PALT calculation appears in participant details section when clicking a point that is above the three times the upper limit of normal, and clicking on PALT causes a footnote to appear.
