### ISSUE TITLE
Demonstrate using the measure_values setting to support additional or alternate measures.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/hep-explorer#303]
For instance, to view another set of four measures this hack _technically_ works:
```
    measure_values: {
        ALT: 'Albumin',
        AST: 'Calcium',
        TB: 'Creatinine',
        ALP: 'Sodium'
    },
```
but the controls still reference _ALT_/_AST_/_TB_/_ALP_.  Need to think through how to generalize things like r-ratio, adding a y-axis control, etc.

**Comment by jwildfire** [comment]
Pretty sure this is already supported for any measure in the raw data (something derived like r-ratio might be harder though). Will see if I can throw together a quick example to demonstrate ...
