### ISSUE TITLE
Option to disable / hide download raw data

### ISSUE THREAD

**Issue by yichen-wang1** [SafetyGraphics/hep-explorer#339]
Hi,
I'm wondering is there maybe an option to disable or hide the download raw data button? Just in case we don't want the users to directly use or see the entire dataset.
Thanks!

**Comment by jwildfire** [comment]
Hi @yichen-wang1 - Setting `config.downloadLink` to false should disable the button. Source code [here](https://github.com/SafetyGraphics/hep-explorer/blob/1388a1e295c1d4f8fc833c83ce5e390bbb2e3d73/src/callbacks/onLayout/addDownloadButton.js#L6C16-L6C28).
